// Datos Mock para desarrollo

export const mockCompanies = [
  {
    id: "1",
    name: "Salón Premium",
    slug: "salon-premium",
    description: "Salón de belleza de lujo",
    logo: "💇",
    primaryColor: "#4F46E5",
    secondaryColor: "#EC4899",
    theme: "light" as const,
    email: "contact@salon.com",
    phone: "+34 900 000 000",
  },
  {
    id: "2",
    name: "Barbería Elite",
    slug: "barberia-elite",
    description: "Barbería profesional para hombres",
    logo: "💈",
    primaryColor: "#1F2937",
    secondaryColor: "#FCD34D",
    theme: "dark" as const,
    email: "contact@barberia.com",
    phone: "+34 900 111 111",
  },
]

export const mockServices = [
  {
    id: "1",
    companyId: "1",
    name: "Corte de cabello",
    description: "Corte moderno y personalizado",
    category: "belleza",
    duration: 30,
    price: 25.00,
    active: true,
  },
  {
    id: "2",
    companyId: "1",
    name: "Peinado especial",
    description: "Peinado para eventos",
    category: "belleza",
    duration: 45,
    price: 45.00,
    active: true,
  },
  {
    id: "3",
    companyId: "1",
    name: "Tratamiento capilar",
    description: "Hidratación profunda",
    category: "belleza",
    duration: 60,
    price: 55.00,
    active: true,
  },
  {
    id: "4",
    companyId: "1",
    name: "Manicura",
    description: "Manicura gel o acrílico",
    category: "belleza",
    duration: 45,
    price: 30.00,
    active: true,
  },
  {
    id: "5",
    companyId: "2",
    name: "Corte barba",
    description: "Recorte de barba profesional",
    category: "barberia",
    duration: 20,
    price: 12.00,
    active: true,
  },
  {
    id: "6",
    companyId: "2",
    name: "Corte + Barba",
    description: "Corte completo con barba",
    category: "barberia",
    duration: 40,
    price: 20.00,
    active: true,
  },
]

export const mockEmployees = [
  {
    id: "1",
    companyId: "1",
    name: "María García",
    email: "maria@salon.com",
    phone: "+34 600 000 001",
    specialty: "Cortes y peinados",
    role: "Estilista",
    commission: 15,
    active: true,
    services: ["1", "2", "3"],
  },
  {
    id: "2",
    companyId: "1",
    name: "Ana López",
    email: "ana@salon.com",
    phone: "+34 600 000 002",
    specialty: "Manicura y pedicura",
    role: "Esteticien",
    commission: 20,
    active: true,
    services: ["4"],
  },
  {
    id: "3",
    companyId: "2",
    name: "Carlos Martínez",
    email: "carlos@barberia.com",
    phone: "+34 600 000 003",
    specialty: "Barbería tradicional",
    role: "Barbero",
    commission: 25,
    active: true,
    services: ["5", "6"],
  },
]

export const mockClients = [
  {
    id: "1",
    companyId: "1",
    name: "Juan Pérez",
    email: "juan@email.com",
    phone: "+34 600 111 111",
    appointments: 5,
  },
  {
    id: "2",
    companyId: "1",
    name: "Rosa Fernández",
    email: "rosa@email.com",
    phone: "+34 600 111 112",
    appointments: 12,
  },
  {
    id: "3",
    companyId: "1",
    name: "Elena Sánchez",
    email: "elena@email.com",
    phone: "+34 600 111 113",
    appointments: 3,
  },
]

export const mockAppointments = [
  {
    id: "1",
    companyId: "1",
    clientId: "1",
    serviceId: "1",
    employeeId: "1",
    date: new Date(2024, 2, 15, 10, 0),
    duration: 30,
    status: "confirmada" as const,
    notes: "Cliente habitual",
  },
  {
    id: "2",
    companyId: "1",
    clientId: "2",
    serviceId: "2",
    employeeId: "1",
    date: new Date(2024, 2, 15, 11, 0),
    duration: 45,
    status: "confirmada" as const,
    notes: "",
  },
  {
    id: "3",
    companyId: "1",
    clientId: "3",
    serviceId: "4",
    employeeId: "2",
    date: new Date(2024, 2, 15, 14, 30),
    duration: 45,
    status: "pendiente" as const,
    notes: "Primera cita",
  },
  {
    id: "4",
    companyId: "1",
    clientId: "1",
    serviceId: "3",
    employeeId: "1",
    date: new Date(2024, 2, 16, 9, 0),
    duration: 60,
    status: "completada" as const,
    notes: "",
  },
]

export const mockTransactions = [
  {
    id: "1",
    companyId: "1",
    type: "ingreso" as const,
    amount: 25.00,
    category: "Servicios",
    description: "Corte de cabello",
    date: new Date(2024, 2, 15, 10, 30),
    appointmentId: "1",
  },
  {
    id: "2",
    companyId: "1",
    type: "ingreso" as const,
    amount: 45.00,
    category: "Servicios",
    description: "Peinado especial",
    date: new Date(2024, 2, 15, 11, 45),
    appointmentId: "2",
  },
  {
    id: "3",
    companyId: "1",
    type: "gasto" as const,
    amount: 150.00,
    category: "Suministros",
    description: "Compra de productos",
    date: new Date(2024, 2, 14, 15, 0),
  },
  {
    id: "4",
    companyId: "1",
    type: "gasto" as const,
    amount: 50.00,
    category: "Mantenimiento",
    description: "Limpieza y mantenimiento",
    date: new Date(2024, 2, 13, 17, 0),
  },
  {
    id: "5",
    companyId: "1",
    type: "ingreso" as const,
    amount: 30.00,
    category: "Servicios",
    description: "Manicura",
    date: new Date(2024, 2, 15, 15, 0),
  },
]

export const mockUsers = [
  {
    id: "1",
    companyId: "1",
    email: "admin@salon.com",
    name: "Admin Salón",
    role: "admin",
  },
  {
    id: "2",
    companyId: "1",
    email: "staff@salon.com",
    name: "Personal Salón",
    role: "staff",
  },
  {
    id: "3",
    companyId: "2",
    email: "admin@barberia.com",
    name: "Admin Barbería",
    role: "admin",
  },
]
